### ISSUE TITLE
The single pipe is not rendered as a white space

### ISSUE THREAD

**Issue by zeraien** [kakulukia/pypugjs#13]
* pypugjs version: 5.3.0

Pug documentation suggests the following code to render white space between tags:
```pug
| Don't
|
button#self-destruct touch
|
| me!
```

However, pypugjs simply renders the pipes unless they are trailed by a whitespace. And since many editors truncate trailing whitespace, this is not practical. Also Pug documentation (2.0.1) claims that the pipe should work without a trailing whitespace.

**Comment by zeraien** [comment]
I think I fixed it 5398ffb0ccc1c87efd769d52be94eef1bde813dd.

**Comment by kakulukia** [comment]
Oh, i thought the PR works as the test shows or did you just forget to close the issue?

**Comment by kakulukia** [comment]
Haha

**Comment by zeraien** [comment]
Well, i created the issue before I created the PR so the issue was kind of disconnected from the PR issue.. it's a mess, I thought I would be able to make the PR from this issue but apparently not, so yeah.

**Comment by kakulukia** [comment]
its actually possible: https://stackoverflow.com/questions/1687262/link-to-the-issue-number-on-github-within-a-commit-message

**Comment by zeraien** [comment]
Yup, but I wasn't sure it was possible across repos, since I created the issue on your repo and committed on mine hehe. Thanks for the tips tho!

Next time ;)
