### ISSUE TITLE
Syntax errors in comments

### ISSUE THREAD

**Issue by brianmhunt** [kakulukia/pypugjs#16]
* pypugjs version: 5.6.0
* Flask version: 1.2.0
* Python version: 2.7

### Description

Using the Jinja2 extension, following the examples/flask:

Content inside comments e.g.  `//-` should be ignored, but it appears they are parsed - meaning syntax errors can cause failure to compile.

### What I Did

Compile a file with this, and it should not syntax error (but it does, with TemplateSyntaxError: unexpected char u'#' at 22).

```
//-  {% if content.#{_.snakeCase(list_name)} %}
```

**Comment by kakulukia** [comment]
thx for reporting, will look into this issue ..

**Comment by kakulukia** [comment]
According to the docs comments look different than you reported (http://jinja.pocoo.org/docs/2.10/templates/#comments). So even in your Flask example it should work with the right comment syntax?
