### ISSUE TITLE
Django compatibility

### ISSUE THREAD

**Issue by grafa** [kakulukia/pypugjs#20]
Hi there

maybe it's worth to mention that pypugjs is compatible with Django 1.11+. On 1.10 I'm getting import error where `from django.utils.translation import template` does not exist.

**Comment by kakulukia** [comment]
Im looking into this. Do you need Django 1.10 compatibility?

**Comment by grafa** [comment]
No, I've just updated. Maybe just update the readme file ;)

**Comment by kakulukia** [comment]
min Django version added to the docs
