### ISSUE TITLE
if - and or operators problem

### ISSUE THREAD

**Issue by mzgs** [kakulukia/pypugjs#21]
* pypugjs version: latest
* Django version: i use flask and jinja
* Python version: 2.7
* Operating System: macOS

### Description

when i try to write if and or else if there is a problem.

### What I Did

here is my code

```
if var1 && var2
     h1 yes

Error : 
jinja2.exceptions.TemplateSyntaxError
TemplateSyntaxError: unexpected char u'&' at 639
```

**Comment by kakulukia** [comment]
Since this is a Python version of Pug, try and instead of &&.

**Comment by mzgs** [comment]
Thank you so much it worked.

**Comment by kakulukia** [comment]
You should close the ticket if solved and leave a star :)
