### ISSUE TITLE
[question] Support for .jade extension

### ISSUE THREAD

**Issue by vlad1777d** [kakulukia/pypugjs#22]
* pypugjs version: 5.6.0
* Django version:
* Python version: 3.6
* Operating System: Linux Mint 19

### Description
I use it with Jinja2 itself.
I see official Pug project supports .jade extension and compiles well to .html.
But I can't see this here in code, only .pug:
https://github.com/kakulukia/pypugjs/blob/d996f50ecb15a3899a94c0011efe32e1b11c1ad6/pypugjs/ext/jinja.py#L99

If yes, I'd like to suggest to support it, or (better) to make possible for users to specify file extensions, which they'd like to process with this extension.

Thank you.
Best regards, Vladislav.

**Comment by vlad1777d** [comment]
@kakulukia , sorrry, I mistaken, that was compiled by official Pug 
(I made python script with watchdog, which compiles my files),
so I forgot to use new class, which used this library, it was compiled with nodejs =).

**Comment by kakulukia** [comment]
So, issue fixed / misunderstanding solved?

**Comment by vlad1777d** [comment]
@kakulukia , yes, close this please.
