### ISSUE TITLE
[question] Does it support absence of commas between attributes

### ISSUE THREAD

**Issue by vlad1777d** [kakulukia/pypugjs#23]
* pypugjs version: 5.6.0
* Django version:
* Python version: 3.6
* Operating System: Linux Mint 19

### Description
My code: https://pastebin.com/UkEJfB3C
or : [login_page.txt](https://github.com/kakulukia/pypugjs/files/2216374/login_page.txt)

Fails with expecting ')' symbol.
As you see, I added several commas between attributes, but it still gives error (they are not everywhere).

Seems, absence of commas - reason of that problem.

Is it so ?

Thank you.

P.S.
If I could understand how it works (I'm confused with regular expressions), I could help you with it.

**Comment by kakulukia** [comment]
Tag are evaluated as Python code and thus there needs to be some sort of separator. Please always use a comma and it will work!

**Comment by vlad1777d** [comment]
@kakulukia , I think, it should be fixed.
Original Pug language supports it.
If not to add commas, than parsed tag should have all attributes in `attrs` variable, but only first attribute in `static_attrs`, which is the reason of the problem, because static ones are rendered to .html.

If to place print here:
`https://github.com/kakulukia/pypugjs/blob/master/pypugjs/parser.py#L313`
Print in first case:
`tok:  {'buffer': None, 'type': 'attrs', 'line': 6, 'val': None, 'inline_level': 0, 'attrs': odict.odict([('rel', "'ic on'"), ('href', "'/static/general/images/favicon_v2.png'"), ('type', "'image/x-icon'")]), 'static_attrs': {'rel', 'href', 'type'}}
`
Print in second case:
`tok:  {'buffer': None, 'type': 'attrs', 'line': 6, 'val': None, 'inline_level': 0, 'attrs': odict.odict([('rel', "'ic on'"), ('href', "'/static/general/images/favicon_v2.png'"), ('type', "'image/x-icon'")]), 'static_attrs': {'rel'}}`

I think, problem is here:
https://github.com/kakulukia/pypugjs/blob/master/pypugjs/lexer.py#L505

If to replace this line to:
`if c in (',', '\n') or (c == ' ' and state() == 'val' and ns.val.strip()):`
, than all attributes will be counted as static ones, and add would be rendered well.

**Comment by kakulukia** [comment]
Well, try to implement that without breaking the tests.

**Comment by kakulukia** [comment]
Anything to report on this feature?

**Comment by vlad1777d** [comment]
@kakulukia , sorry, I had not time to do it yet.
I just made that hot fix to work on site further, but had not time to check tests.

I'll do it soon, when I'll have some free time.

**Comment by kakulukia** [comment]
You could just send a pull request and let Travis do the testing. :)

**Comment by kakulukia** [comment]
> How to launch tests locally ?

Have a look at the end of the readme `make init` and `make test`.

> Also I don't see any requirements.txt, how to install all that stuff ?)
> Maybe it would be better to use pipenv for such cases.

`make init` is taking care of the and uses `pipenv`. Hence the Pipfile in the project root. :)

**Comment by kakulukia** [comment]
Run `make` to see all the options.

**Comment by vlad1777d** [comment]
Seems it work now, so closing.
Fixed by: https://github.com/kakulukia/pypugjs/pull/31

**Comment by kakulukia** [comment]
Well done, sweet!
