### ISSUE TITLE
Unicode chars not properly encoded when include file 

### ISSUE THREAD

**Issue by Dryja** [kakulukia/pypugjs#24]
* pypugjs version: 5.6.0
* Python version: 3.6.6
* Operating System: Win 10 (I think it is not os related bug)
* jinja + flask
### Description
Hey
I think there is a issue with unicode encoding. When I use include a pug file utf-8 encoding are not properly handled. It results in broken chars.  Anyway just look below to see what's happening.

### What I Did
I think it is best to present this bug with an example:

demo.pug 
```
doctype html
html(lang="en")
  head
    meta(charset="utf-8")
  body
    p ąść 
    include demo1.pug
```
demo1.pug
```
p ąść
```

And after rendering it I get:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <p>ąść </p>
    <p>Ä…Ĺ›Ä‡</p>
  </body>
</html>
```

I will try to fix this bug by myself and then commit change, but I wanted to report that there is a issue.

**Comment by kakulukia** [comment]
I never encountered problems like this, could you try different editors?

Waiting for a PR then. :)

**Comment by Dryja** [comment]
@kakulukia 
Rendering directly in flask gives the same result.

**Comment by Dryja** [comment]
Hm it's strange, I am now testing it on Ubuntu and it is working fine. So it looks that it is os related lol.

**Comment by Dryja** [comment]
Okay, I found the issue. It is os related.

On Windows 10:
```
>> import locale
>> locale.getpreferredencoding()
'cp1250'
```
that's why changing 85 line in ext/jinja.py 
to 
```
src = open(path, 'r', encoding='utf-8').read()
```
solves problem with encoding. 

I assuming that the problem occurs also in different ext files.

**Comment by kakulukia** [comment]
Looks like an overdue correction to me. 🤣

**Comment by kakulukia** [comment]
What about that mentioned PR of yours? @Dryja 
Im back from my vacations and wanted to fix that bug. :) Please publish your code.

**Comment by kakulukia** [comment]
Version 5.7.0 should fix that problem - please close it it does.
