### ISSUE TITLE
Template Does Not Exist

### ISSUE THREAD

**Issue by jhotujec** [kakulukia/pypugjs#28]
* pypugjs version: Latest
* Django version: 1.9
* Python version: 2.7.1
* Operating System: Docker Ubuntu Based Image

### Description

I have two templates, in two separate folders under. One is called 'default.pug' under `/templates/layouts/default.pug` folder in django project, the other one is called `homepage.pug` inside an app(posts).

### What I Did
> default.pug
```
extends 'layouts/base.html'

block content

    include 'partials/header.html'
    include 'partials/notifications.html'
    include 'partials/page_header.pug'

    block subcontent

<!-- Footer -->
include 'partials/footer.html'
```
> homepage.pug
```
extends 'layouts/default.pug'
```

Im getting 

`TemplateDoesNotExist at /layouts/default.pug`

**Comment by jhotujec** [comment]
this can be closed, it was a typo on my end

**Comment by kakulukia** [comment]
:)
