### ISSUE TITLE
[Question] Dynamic Attributes

### ISSUE THREAD

**Issue by vcandeau** [kakulukia/pypugjs#30]
* pypugjs version: 5.1.7
* Python version: 3.7
* Pyramid: 1.9.2

Why i can not use the &attirubtes snippet.
Wrote this:
` a.tile(data-size="medium", data-role="tile", class="bg-#{items[item]['color']}", data-vsct-percent="#{items[item]['percent']}", href="#{hrefUrl}")&attributes({"data-toto": 1, "data-tata": 2})`

Waiting for
` a.tile(data-size="medium", data-role="tile", class="bg-#{items[item]['color']}", data-vsct-percent="#{items[item]['percent']}", href="#{hrefUrl}", "data-toto"="1", "data-tata"="2")`

Thx for answering

**Comment by kakulukia** [comment]
Well, I’m not aware that this feature exists in pypugjs, since it’s based of jade from around 3 years ago. 
You are welcome to implement this and send a pull request, tho!

**Comment by vcandeau** [comment]
I will do this :)

**Comment by kakulukia** [comment]
Nice!

**Comment by kakulukia** [comment]
Any news on this?
I will close the ticket - if you get it working, just send in a pull request. :)
