### ISSUE TITLE
generating attributes with parentheses and brackets should work to support Angular 

### ISSUE THREAD

**Issue by argolo** [kakulukia/pypugjs#32]
* pypugjs version: 5.7.2
* Django version: None
* Python version: 3.7.0
* Operating System: Mac OS High Sierra, Version 10.13.6

### Description
I'm getting input with attributes with parentheses in their syntax. It is valid in https://html2jade.org but is failing in pypugjs. Would you have something to do to give support?

PS: I'm using the python interpreter.

### What I Did

```python
>>> import pypugjs
>>> text = 'input((blur)="foo()" type="text")'
>>> pypugjs.simple_convert(text)
'\n<input blur="()"foo()"" type="text"/>'
```

#### In pug
```pug
input((blur)="foo()" type="text")
```

#### Out pug
```pug html
<input (blur)="foo()" type="text" />
```

**Comment by kakulukia** [comment]
Why are you using that syntax and what are the supposed benefits?

**Comment by argolo** [comment]
> Why are you using that syntax and what are the supposed benefits?

This is the syntax used in Angular 4+. It is required for "Types of Event Binding".

**Comment by kakulukia** [comment]
Okay, but for curiosity: why are you not using the native pug lib with Angular instead of this library?

**Comment by argolo** [comment]
> Okay, but for curiosity: why are you not using the native pug lib with Angular instead of this library?

Good question (laughs). It may seem strange, but I need to serve the Angular 4+ model with Flask, and I'm looking to do this with Python because it will be more efficient for my needs.

**Comment by kakulukia** [comment]
Sounds fair. 
My first suggestion is: use VueJS instead!

As I said it multiple times before: I think the pypugjs parser was setup in weird ways and I can’t promise you a quick fix, since currently I have lots of other stuff to do. 
But let’s add a label to this ticket.

**Comment by kakulukia** [comment]
Cool!

**Comment by argolo** [comment]
I have found that, commenting on these lines, the operation is more like running **pugjs**. But in the tests I have seen that **pypugjs** has its own implementations, which run out of the syntax of **pugjs**, as "variables" (if I may call it that). And these implementations require this treatment presented in the lines below.

I have not found an easy way to maintain dual support. So I'll leave that record here.

**Line 568 to 593 from pypugjs/lexer.py**

```python
568             elif '(' == c:
                    print(ns, c, states)
                    if state() in ('val', 'expr'):
                        states.append('expr')
                    ns.val += c
                elif ')' == c:
                    print(ns, c, states)
                    if state() in ('val', 'expr'):
                        states.pop()
                    ns.val += c
                elif '{' == c:
                    if 'val' == state():
                        states.append('object')
                    ns.val += c
                elif '}' == c:
                    if 'object' == state():
                        states.pop()
                    ns.val += c
                elif '[' == c:
                    if 'val' == state():
                        states.append('array')
                    ns.val += c
                elif ']' == c:
                    if 'array' == state():
                        states.pop()
593                 ns.val += c
```

**Comment by kakulukia** [comment]
Could you name those tests? I will have a look at them. Sad thing that it’s not documented.

**Comment by argolo** [comment]
> Could you name those tests? I will have a look at them. Sad thing that it’s not documented.

I no longer remember what the tests were, but I'm trying to find a solution. I am trying to differentiate the values of an attribute in "key" and "value". So I think I can leave a "key" without this treatment and make it work.

**Comment by kakulukia** [comment]
Sounds good, but honestly i dont know what that other syntax feature might be. o.O

**Comment by kakulukia** [comment]
Any new on this issue?
I will close it for now - if you get it working, i will gladly merge the new pull request. :)
