### ISSUE TITLE
Enhancing the command line compiler

### ISSUE THREAD

**Issue by rezpe** [kakulukia/pypugjs#33]
* pypugjs version: 5.7.2
* Python version: 2.7
* Operating System: Ubuntu 16

### Description

I am trying to use the bootstrap pug templates from this repository (https://github.com/mike-goodwin/pug-bootstrap/blob/master/_bootstrap.pug) but I get errors and I am not able to see the problem. Is the PUG there not supported ? It works with pug executable in npm.

### What I Did

```
git clone https://github.com/mike-goodwin/pug-bootstrap
cd pug-bootstrap
pypugjs _bootstrap.pug -c html
--> Error Messages
--> Exception: Include path doesn't exists
```

**Comment by kakulukia** [comment]
Im going to check that tonight ..

**Comment by kakulukia** [comment]
Oh, that pug packages make heavy use of mixins, which are not supported by the command line compiler. Sorry, but its a little bit out of date and thus you should better use the npm version.

I wouldnt call compiling a bootstrap pug lib a simple file with includes, tho! 
That is quite complex stuff.

**Comment by rezpe** [comment]
I see. Can you help me and let me know what is not supported by the lib ? Is it just the mixins or vars ?

**Comment by kakulukia** [comment]
Mainly the mixins part, but im not that familiar with the command line compiler. What are you trying to build? Maybe there is a better solution to get to your goal.

**Comment by rezpe** [comment]
The idea would be to build a website in bootstrap from the jupyter notebook by combining building blocks in pug-bootstrap. So you would write the pug and then with a method get the html of the website.

```python
pug_content = """
+cover("Analysis on Data")
row
   col-4
       Lorem Ipsun
   col-8
       chart
"""
html = render_pug(pug_content)
from ipython.display import HTML
HTML(html)
```

**Comment by kakulukia** [comment]
Well, try to use the Jinja2 template extension rather than the command line compiler .. this should help you get the mixins working.

**Comment by kakulukia** [comment]
You misunderstood me. Please use the jinja2 template engine inside your code rather than the command line tool and add the pug extension to jinja2.

**Comment by rezpe** [comment]
Can you write some pseudo-code to understand what you mean ?

**Comment by kakulukia** [comment]
Install the jinja2 lib

    pip install jinja2

Create a `test.py` like this:

    from jinja2 import Environment, FileSystemLoader
    env = Environment(
        loader=FileSystemLoader('.'),
        extensions=['pypugjs.ext.jinja.PyPugJSExtension']
    )
    template = env.get_template('test.pug')
    print(template.render(name="World"))

While `test.pug` looks like this:

    .foo Hello {{ name }}!

**Comment by kakulukia** [comment]
I also enhanced the jinja2 installation paragraph here https://github.com/kakulukia/pypugjs/blob/master/docs/installation.rst

**Comment by kakulukia** [comment]
Hope that helps!

**Comment by rezpe** [comment]
Hi, 

   Using pugbootstrap as it is, it gives an error ... It's a pity it would have been cool to reuse that project and combine it with yours. 
It would have enabled to generate a website in no time with additional charts generated in python. 
One option would be to create a fork of pugbootstrap that is compliant with your library. You might want to take a look at it (link in the conversation above) and tell me what you would change. I would then try to do the fork and the changes.

Regards,
Sebas

**Comment by kakulukia** [comment]
Whats the error?
The same as with the command line tool?

**Comment by kakulukia** [comment]
Since there was no answer in quite a few days, im closing that ticket.

**Comment by rezpe** [comment]
Hi, Sorry for not answering. Yes, the error was the same, but I believe it's not worth it to solve this as it was faster to adapt the pug code organization to this tool. Thanks a lot for the support

**Comment by kakulukia** [comment]
you are welcome! :)
