### ISSUE TITLE
{% trans %} doesn't work! 

### ISSUE THREAD

**Issue by NursErgesh** [kakulukia/pypugjs#39]
* pypugjs version:pypugjs==5.7.2
* Django version:Django==2.0.9
* Python version:Python 3.7.0
* Operating System: Mac

### Description

I wanted to use {% trans %} templatetag for translating static text

### What I Did

```
.slider-text
     .slider-text-inner
         h1 ЭМАКОМ
             span |{% trans "строительная компания" %}

```
```
./manage.py makemessages
bash -cl "/Users/noors/venvs/emakom/bin/python /Applications/PyCharm.app/Contents/helpers/pycharm/django_manage.py makemessages /Users/noors/PycharmProjects/emakom"
processing locale kg
```

**Comment by MrCordeiro** [comment]
Silly question, but you are loading `i18n` after the `extends` in this file, right?

`-load i18n`

**Comment by kakulukia** [comment]
Right

**Comment by kakulukia** [comment]
Did you enable translations as documented?

**Comment by NursErgesh** [comment]
SOLVED!
I just indicated file extension
./manage.py makemessages -e pug -e py

**Comment by kakulukia** [comment]
You can as well use -e py,pug .. if you think, its not documented well enough, feel free to reopen. :)
