### ISSUE TITLE
Iteration problem

### ISSUE THREAD

**Issue by chiboreache** [kakulukia/pypugjs#42]
Hi there! 

I've got this:
`jinja2.exceptions.TemplateSyntaxError: expected token ':', got '}'`

![screenshot_20181215_083439](https://user-images.githubusercontent.com/16459251/50039479-43655000-0044-11e9-8602-5b64ca9e9e47.png)

**Comment by chiboreache** [comment]
that's provide cleaner result, but steel doesn't work

```ul
  for value in values
    li= value
```

this is really the issue


```__pypugjs_iter()```

**Comment by chiboreache** [comment]
here is my workaround, looks ugly, but works

![screenshot_20181220_202310](https://user-images.githubusercontent.com/16459251/50300334-2510b180-0495-11e9-9625-8e28534a0409.png)

**Comment by kakulukia** [comment]
Since you already found a solution, im closing that ticket. If curly braces interfere with each other, its most of the times possible to change one or the other syntax of either template rendering steps.
