### ISSUE TITLE
Inline Javascript problem

### ISSUE THREAD

**Issue by BarnabasSzabolcs** [kakulukia/pypugjs#43]
* pypugjs version: 5.7.2
* Django version: 2.1.4
* Python version: 3.6
* Operating System: OSX

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

The "script." tag only works fine until it meets "</script>" because it interprets it as a closing tag,
instead of interpreting it as a string.
(This thing may look silly - my intention was to load fb async as to decrease google page load time adn js.async didn't work so I tried placing the whole script to be loaded after pageload.)

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
script.
        document.addEventListener('load', function(){
            "<script>" +
            "(function(d, s, id) {" +
              "var js, fjs = d.getElementsByTagName(s)[0];" +
              "if (d.getElementById(id)) return;" +
              "js = d.createElement(s); js.id = id; js.async = true;" +
              "fjs.parentNode.insertBefore(js, fjs);" +
              "}(document, 'script', 'facebook-jssdk'));" +
              "</script>"});
resulted in 
<script>document.addEventListener('load', function(){
    "<script>" +
    "(function(d, s, id) {" +
      "var js, fjs = d.getElementsByTagName(s)[0];" +
      "if (d.getElementById(id)) return;" +
      "fjs.parentNode.insertBefore(js, fjs);" +
      "}(document, 'script', 'facebook-jssdk'));" +
      "</script>
});

**Comment by kakulukia** [comment]
Why are you using that script tag in the first place rather than continuing with javascript?

**Comment by kakulukia** [comment]
Can you clarify that? Otherwise im closing the ticket ..

**Comment by BarnabasSzabolcs** [comment]
I'm not using the script tag. I use a JS string that happens to contain "<script>".

**Comment by BarnabasSzabolcs** [comment]
nevermind, I've found the solution. The issue is not with pug.
Here is an explanation: 
https://stackoverflow.com/questions/33969544/can-i-write-a-script-tag-inside-a-script-tag
