### ISSUE TITLE
PyPugJS doesn't work with django cached template loader

### ISSUE THREAD

**Issue by melinath** [kakulukia/pypugjs#44]
* pypugjs version: 5.7.2
* Django version: 1.11.12
* Python version: 2.7
* Operating System: Linux

### Description

If you want to use django cached loader with pypugjs, you'd have the following template loader settings:

```
('django.template.loaders.cached.Loader', [
    ('pypugjs.ext.django.Loader', [
        'django.template.loaders.filesystem.Loader',
        'django.template.loaders.app_directories.Loader',
    ]),
])
```

With pypugjs 4.2.2 this worked fine, but with 5.7.2 it doesn't, because the pug processing of contents never happens.

Here's the code in 4.2.2: https://github.com/kakulukia/pypugjs/blob/4.2.2/pypugjs/ext/django/loader.py#L101
The loading of the template uses child loaders to get contents, then processes them, then returns a template with an origin and the processed contents.

In 5.7.2 this process has been updated to work with the new django get_template_sources and get_contents methods. In my example, the following will happen:

1. Django cached loader get_template_sources is called
2. Django cached loader delegates to children
3. PyPugJS delegates to children and returns the origin(s) they return. The origins' loader will be set to the child loader, not pypugjs.
4. [Django cached loader get_contents is called with the returned origin](https://github.com/django/django/blob/1.11.12/django/template/loaders/cached.py#L28). This results in the origin's loader (for example, the filesystem loader) returning an unprocessed pug string rather than going through the PyPugJS get_contents() method which would have converted the pug to django-compatible html.

**Comment by kakulukia** [comment]
Its sounds like you traced the issue well enough to also supply a pull request?

**Comment by kakulukia** [comment]
Actually PyPugJS is also caching templates, so the need for the cached loaded should not exist.

**Comment by tjwalch** [comment]
In #50 I replaced the old PyPugJS caching that was buggy by sub-classing Django's `cached.Loader`, but bypassing caching in debug mode. Just like the default Django behavior.

**Comment by melinath** [comment]
We ended up removing pypugjs from our project, so I can't verify the fix for you, but it sounds like the changes you've made probably would have resolved our issue.

**Comment by snarfed** [comment]
we're seeing this problem too, on pypugjs 5.8.1 with both django 1.11 and 2.2. cc @justinwang189. if i set `DEBUG` to `True` to disable caching, it disappears.

based on https://github.com/kakulukia/pypugjs/pull/50#issuecomment-487547123, it sounds like @tjwalch's fix in #50 made it into 5.8.1, so it must not have fixed this, or at least not for us.

not sure what we'll do yet, but i'll update here once we've figured it out.

**Comment by kakulukia** [comment]
Yes, its in the new release.
@tjwalch did 5.8.1 fix the problem for you?
@snarfed you might experience an edge case of that same error?

Well, since the Loader is doing the conversion, replacing it has to result in the pug source to not be processed .. sadly i didnt have time yet to have a look at what the last fix did.

**Comment by tjwalch** [comment]
Yes, it works well for me. I can look into it some more, though I need some more info. @snarfed - just to be sure, you are not using `django.template.loaders.cached.Loader` separately are you?

**Comment by snarfed** [comment]
@tjwalch ah! good catch, we were doing exactly that. apologies for the false alarm! i believe removing that fixes it for us. i'll post back later when i know more. thanks, great guess!

**Comment by kakulukia** [comment]
@snarfed: could you enhance the documentation to make sure nobody falls into the same pit?
@tjwalch: is the current config documentation still valid regarding your changes?

**Comment by tjwalch** [comment]
Yes, but as everyone noticed maybe not explicit enough.

**Comment by snarfed** [comment]
@kakulukia sure! done, #52.

**Comment by kakulukia** [comment]
Thx!

**Comment by BarnabasSzabolcs** [comment]
I'm late to the party... now, I'm wondering... in the newest version, does pypugjs.ext.django.Loader cache the template when DEBUG=False?

**Comment by kakulukia** [comment]
@tjwalch ?
Im note sure with the latest changes. 🧐

**Comment by tjwalch** [comment]
It does. 
`pypugjs.ext.django.Loader` is now a subclass of `django.template.loaders.cached.Loader`
