### ISSUE TITLE
how to call super() as in Jinja2 ?

### ISSUE THREAD

**Issue by gotexis** [kakulukia/pypugjs#45]
#{ super() }

doesn't work..

**Comment by kakulukia** [comment]
i dont recognise that syntax .. please explain, how you did setup your environment and how you are using pypugjs

**Comment by gotexis** [comment]
Haha thanks for the prompt response.

I believe in jinja2 we need to call { super() } to include the parent block's content.


After digging into the pug documentations, I figured the correct syntax is ' block extend  '

**Comment by kakulukia** [comment]
so the issue is resolved?

**Comment by gotexis** [comment]
Yes!

**Comment by kakulukia** [comment]
Then you should close it.
