### ISSUE TITLE
Improvement to inline JS instruction

### ISSUE THREAD

**Issue by gotexis** [kakulukia/pypugjs#46]
I found the following won't work if I don't put a trailing ". " (full stop) after script.
```pug
    script(type='text/javascript')
      if (foo) {
         bar()
      }
```

should be:

```pug
    script(type='text/javascript').
      if (foo) {
         bar()
      }
```

Not sure why this is the case though...

**Comment by kakulukia** [comment]
this  works as intended - see https://pugjs.org/language/plain-text.html > Block in a Tag

**Comment by gotexis** [comment]
Yes, but I was trying to say the README.rst of the project does not show the ". "

**Comment by kakulukia** [comment]
Glad you fixed it!
