### ISSUE TITLE
Is it possible to use PyPugJs just from within Python without a Framework?

### ISSUE THREAD

**Issue by 00SteinsGate00** [kakulukia/pypugjs#48]
* pypugjs version: latest
* Python version: 3.6.5
* Operating System: MacOS 10.14.2

### Description

I'd like to compile a template file from within Python, not from the command line. I'd actually just like to know if it's possible :) 
### What I Did

I tried using the `Compiler` class but I couldn't find out what that `node` object is that the constructor takes.

**Comment by kakulukia** [comment]
Well actually that should be possible, since there is this command line compiler, you might check, how this is triggering the template translation process. I never used this so i cant tell you right now, but this hint might help.

**Comment by 00SteinsGate00** [comment]
Thanks for the response. I was actually able to figure it out by looking at the `jinja_example.py` file. However it seems that the `Compiler` is not able to fill it variables and stuff, it seems to just process `pug` into another HTML Template language processable by **Django**, **Flask** and so on.

I was looking for a Pug Compiler that compilers pug straight into html, my project is not big, so I'll just create the html myself I guess :) Thanks for the help
