### ISSUE TITLE
How to use  PyPugJs from Python without a Framework? 

### ISSUE THREAD

**Issue by anatolyrossinsky** [kakulukia/pypugjs#53]
* pypugjs version: 5.8.1
* Django version: --
* Python version: 3.3.7
* Operating System: MacOs 10.14.4

### Description

I don't want to install Jinja2 etc. Can i Just use PyPugJS -> HTML with variables interpolation? 

### What I Did

```
...
html=f.read()

pageTitle = 'TTTTTTTTT'
print(pypugjs.ext.html.process_pugjs (html ))   
```

expected output:
```
<title>TTTTTTTTT</title>
```

but i got:
```
<title>None</title>
```

**Comment by kakulukia** [comment]
Well, pypugjs is really just rewriting pug into valid HTML. The template engines like Jinja2 are doing the variable magic. So i fear there is no way for you to fake that.

**Comment by anatolyrossinsky** [comment]
Thanks. I just add Jinja2 to pipeline. This is  true unix way :)

**Comment by char101** [comment]
It is possible

```python
def compile_pug(template, vars, **options):
    parser = pypugjs.parser.Parser(template)
    block = parser.parse()
    compiler = pypugjs.ext.html.Compiler(block, pretty=True, **options)
    compiler.global_context = vars
    return compiler.compile()
```

**Comment by kakulukia** [comment]
Interesting! This could be added as a helper function, if the need is higher than just two persons. :)

**Comment by char101** [comment]
I put it there so that the 3rd person could copy paste it ;)
