### ISSUE TITLE
Please git push --tags for users to get latest tagged tarballs

### ISSUE THREAD

**Issue by dol-sen** [kakulukia/pypugjs#59]
I am looking to package this for Gentoo as a substitute for pyjade dependency for buildbot.

```

**Comment by kakulukia** [comment]
What exactly are you missing?
All tags are pushed and visible here: https://github.com/kakulukia/pypugjs/tags

**Comment by dol-sen** [comment]
the last tag there is 5.8.1.  Your latest release in the code and pypi is 5.9.1

**Comment by dol-sen** [comment]
Thank you :)
