### ISSUE TITLE
Broken PyPi packages

### ISSUE THREAD

**Issue by tjwalch** [kakulukia/pypugjs#6]
* pypugjs version: All > 5.1.1
* Django version: 1.11
* Python version: 2.7, 3.5
* Operating System: Linux, Windows

### Description

The packages in PyPi are broken, they don't contain the `ext` directory.

### What I Did

```
pip install -U pypugjs
```

## Result

````
File "/path/to/virtualenv/lib/site-packages/pypugjs/__init__.py", line 5, in <module>
    from .ext import html
ImportError: No module named ext

**Comment by kakulukia** [comment]
i have an idea whats causing this .. let me check ..

**Comment by kakulukia** [comment]
please test the new version 5.3.0

**Comment by tjwalch** [comment]
`ext` is back :-) Thank you for the quick fix and for taking in maintenance of this package generally,

**Comment by kakulukia** [comment]
please also leave a star! :D

**Comment by kakulukia** [comment]
haha .. no thumb .. i mean this https://github.com/kakulukia/pypugjs/stargazers feature to raise visibility of this package again!

**Comment by kakulukia** [comment]
oh .. i just followed you profile and saw that you could actualy do me a favour in return:
https://github.com/tjwalch/django-livereload-server/issues/9 :)

i still love the reload server
