### ISSUE TITLE
`pypugjs.ext.html.Compiler` does not escape

### ISSUE THREAD

**Issue by wwoods** [kakulukia/pypugjs#65]
* pypugjs version: 5.9.4

`pypugjs.ext.html.Compiler.interpolate` never uses the `escape` parameter, which is inconsistent with Pug templating.

Fix is easy -- change replacement to escape if escape is set.

**Comment by kakulukia** [comment]
Please elaborate a little more. What's that parameter good for / what are you trying to do? Could you supply a test case?
