### ISSUE TITLE
Source distribution not published on PyPI

### ISSUE THREAD

**Issue by lopsided98** [kakulukia/pypugjs#68]
I was working on packaging this for nixpkgs, and noticed that there is no source tarball published on PyPI. We prefer to build from source tarballs rather than use wheels. It's not a big problem since we can just pull from the GitHub repo, but I just wanted to let you know as it is standard practice for Python packages to include a source tarball and would be helpful for us in the future. Thanks.

**Comment by kakulukia** [comment]
Im not sure what that means for the build script. But please have a look (https://github.com/kakulukia/pypugjs/blob/master/Makefile) and suggest the necessary addition to it.

**Comment by lopsided98** [comment]
I think you just need to add `sdist` along with `bdist_wheel` here: https://github.com/kakulukia/pypugjs/blob/master/Makefile#L70. That is what is shown in the example in the documentation: https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives

**Comment by kakulukia** [comment]
Im adding this, but have to wait for some content to meaningfully test this with the next release.

**Comment by kakulukia** [comment]
Please check the latest release to see if it worked.

**Comment by lopsided98** [comment]
Sorry, I should have tested my suggestion. The source tarball is published, but it is missing the `docs/HISTORY.rst` file loaded by `setup.py`, so it can't be installed. #70 fixes that and I have confirmed that installation now works with that PR.
