### ISSUE TITLE
Dynamic access of dict in template

### ISSUE THREAD

**Issue by tmzhuang** [kakulukia/pypugjs#75]
* pypugjs version: 5.8.1
* Django version: 3.0.2
* Python version: 3.7.4

### Description
I have the following mixins:
```
mixin get_branch_select_form(name)
    if branches
        select.form-control.selectpicker.mr-1(
        name='{{name}}_branch'
        id='branch-select-form-{{name}}'
        data-selected-text-format='count' data-live-search='true'
        title='Select a branch' onchange='onBranchSelectChange(this)')
            each branch in branches
                if filter["{{name}}_branch"] == branch.pk
                    option(value='{{ branch.pk }}', selected)= branch
                else
                    option(value='{{ branch.pk }}')= branch

mixin get_group_select_form(name)
    if groups
        select.form-control.selectpicker.mr-1(
        name='{{name}}_group',
        id='group-select-form-{{name}}'
        data-live-search='true' data-actions-box='true'
        title='Select a group' onchange='this.form.submit();')
            each group in groups
                if filter["{{name}}_group"] == group.pk
                    option(value='{{ group.pk }}', selected).
                        #{group.created_at|date:"CREATED_AT_DATETIME"} - #{group}
                else
                    option(value='{{ group.pk }}').
                        #{group.created_at|date:"CREATED_AT_DATETIME"} - #{group}
```
I'd like to have dynamic access to the filter context variable. For example, filter is a defaultdict with indices "reference_group" and "target_group". I'd like to access the dict with something like filter["{{name}}_group"] with name passed in a variable. However, this doesn't seem to work. Not too sure if this is unsupported or I just don't have the correct syntax.

**Comment by kakulukia** [comment]
Maybe you can use the with statement to sign the needed variable? Did you try that?

**Comment by tmzhuang** [comment]
Not familiar with the "with statement". I did get a working implementation though. I assign the value in javascript using - var. Eg.
```
- var key = filter[name + "_group"]
if key == group.pk
...
```
Not the prettiest, but it works. Is a with statement better for this case?

**Comment by kakulukia** [comment]
Here are the docs: https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#with .. but your solution looks kinda the same. Good enough if you ask me.

**Comment by tmzhuang** [comment]
Awesome thanks for the help. Given that there's a decent work around, I consider this matter closed.
