### ISSUE TITLE
Django include TemplateDoesNotExist

### ISSUE THREAD

**Issue by paulhersch** [kakulukia/pypugjs#76]
* pypugjs version: 5.9.12
* Django version: 4.2
* Python version: 3.11.1
* Operating System: NixOS 23.05 (x86-Linux)

### Description
I wanted to use include to use mixins

### What I Did

Install pypugjs as per instructions:
settings.py:
```py
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'loaders': [
                ('pypugjs.ext.django.Loader', (
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ))
            ],
            'builtins': [
                'pypugjs.ext.django.templatetags',
            ],
        },
    },
]
```
my directory structure inside the templates folder (the relevant parts at least)
```
├── base.pug
├── mixins
│  └── button.pug
├── persons
│  └── add.pug
```
base.pug does not use includes

persons/add.pug:
```pug
{% extends "base.pug" %}
include mixins/person.pug
      ...
```
button.pug:
```pug
mixin button(href, text)
    a(href=href, class="button button--primary")
        span(class="button__text")= text
```

### Problem
When i try to load persons/add.pug i get a "TemplateDoesNotExist" Error. As soon as i remove the include from add.pug this error is gone and the page is rendered (minus the mixins). `manage.py find_template mixins/button.pug` can indeed find the Template. Funnily enough the TemplateDoesNotExist also points to the `add.pug` file not being found, although this one can be loaded if the include is commented out.

As i also saw someone using relative paths to resolve includes i tried that as well (`include ../mixins/person.pug`) but this gives me an Index Error here: https://github.com/kakulukia/pypugjs/blob/master/pypugjs/ext/django/loader.py#L22 which makes even less sense to me (i also don't want to rely on relative paths for this so i would prefer to be able to use the the include statement from above).

Do you have any idea what might cause this weird issue?

#### Minimal example
this one doesn't work for me as well (with the same errors mentioned above):
test.pug:
```pug
include test2.pug
a#test
    | this is a
    +a()
```
test2.pug
```
mixin a()
    span() test string
```

**Comment by paulhersch** [comment]
that's alright, would you mind adding a note to the README then? I think this would help save time for someone who is stuck and thinks that their setup is the problem.
i implemented the functionality i needed via djangos templating system now, which is the "proper" way in django anyways i think

**Comment by kakulukia** [comment]
okay, i will close the ticket again after the note has been added. Feel free to supply a suggestion (PR).
