### ISSUE TITLE
Feature request:   `include:markdown-it`

### ISSUE THREAD

**Issue by Zulko** [kakulukia/pypugjs#8]
* pypugjs version: Github version
* Python version: 3.5
* Operating System: Ubuntu

Hi there and thanks for the effort in maintaining a very useful library.

There is a feature in Pug allowing to ``include`` a file while filtering its content.
It allows to import files in formats other than Pug, for instance markdown.
See [this page](https://pugjs.org/language/includes.html#including-filtered-text) for this example:

```
doctype html
html
  head
    title An Article
  body
    include:markdown-it article.md
```
Right now, this code in pypugjs gives a body with just a text ``article.md``. That's because pypugjs believes that ``include:markdown-it`` is a tag and ``article.md`` is a content.

Of course in the example above 'markdown-it' is not registered with pypugjs, but I also tried with a simple pre-registered filter ``capitalize`` and the result is the same

How difficult would it be to make this Pug feature work with pypugjs ? I am happy to help if you point me in the direction.

**Comment by KittenHero** [comment]
I can help implement the lexer and the parser but since each extension has it's own `visitInclude` it'll be a pain to do

**Comment by kakulukia** [comment]
you dont have to do implement them all .. it hasnt been done before as you can see in this section https://github.com/kakulukia/pypugjs/blob/e694f4e0080936de162960ef70abd4a3fd7e60f3/pypugjs/testsuite/test_cases.py#L191

**Comment by KittenHero** [comment]
oh, I didn't notice that there were test exclusions lol :+1: , i actually mucked with the html mixin to make it conform to the other format and be bad in my PR, should have just excluded it from the test
