### ISSUE TITLE
-trans and -blocktrans tags aren't picked up in .jade files

### ISSUE THREAD

**Issue by egor83** [kakulukia/pypugjs#86]
* pypugjs version: 5.8.1
* Django version: 2.2.27
* Python version: 3.8.10
* Operating System: Ubuntu 20.04.6 (MATE)

### Description

I ran `makemessages` to collect strings for translations. We are using .jade files, so I ran it as follows:
`python manage.py makemessages -e py,html,jade`

`{% trans %}` and `{% blocktrans %}` tags were picked up fine, but `-trans` and `-blocktrans` weren't.
Once the files were renamed to .pug, the tags were picked up fine.

`decorate_templatize` function called by `enable_pug_translations()` from the readme is hardcoded to only handle .pug files:
https://github.com/kakulukia/pypugjs/blob/master/pypugjs/ext/django/compiler.py#L84

Not sure if just extending this check would solve the issue.
But if PyPugJS only works with .pug and not .jade files, maybe a mention in readme would help?

### What I Did

```
$ python manage.py makemessages -e py,html,jade
processing locale en
```

**Comment by kakulukia** [comment]
Hi,
as the renaming from jade to pug was quite a while ago (i just looked it up - 8 years), i did not bother to include the old extension. Is it a problem for you to raname all the files to .pug?

**Comment by egor83** [comment]
I've already done this - just wanted to leave a note in case someone runs into the same problem.

If you don't think a note about .jade files in readme is warranted, I think the ticket can be closed.

**Comment by kakulukia** [comment]
I will add it.

**Comment by egor83** [comment]
Thanks for this, and for all your work on the project! :)

**Comment by kakulukia** [comment]
Thanks!
